# Generated by Django 2.1.7 on 2019-03-06 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nekretnina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(choices=[('Kuća', 'Kuća'), ('Stan', 'Stan'), ('Stambeno poslovni prostor', 'Stambeno poslovni prostor'), ('Plac', 'Plac'), ('Lokal', 'Lokal'), ('Garaža', 'Garaža')], max_length=100)),
                ('mesto', models.CharField(max_length=250)),
                ('ulica', models.CharField(blank=True, max_length=250, null=True)),
                ('lokacija', models.CharField(choices=[('-', '-'), ('Bair', 'Bair'), ('Bare', 'Bare'), ('Donji Šor', 'Donji Šor'), ('Preki Šor', 'Preki Šor'), ('Živinarnik', 'Živinarnik'), ('Trkalište', 'Trkalište'), ('Šipurske Livade', 'Šipurske Livade'), ('Kasarske Livade', 'Kasarske Livade'), ('Južna Karolina', 'Južna Karolina'), ('Čavić', 'Čavić'), ('Centar', 'Centar'), ('Kamenjak', 'Kamenjak'), ('Kamičak', 'Kamičak'), ('Triangla', 'Triangla'), ('Letnjikovac', 'Letnjikovac')], max_length=250)),
                ('cena', models.PositiveIntegerField()),
                ('povrsina', models.PositiveIntegerField()),
                ('opis', models.TextField(max_length=1500)),
                ('struktura', models.CharField(choices=[('-', '-'), ('0.5', '0.5'), ('1.0', '1.0'), ('1.5', '1.5'), ('2.0', '2.0'), ('2.5', '2.5'), ('3.0', '3.0'), ('3.5', '3.5'), ('4.0', '4.0'), ('4.5', '4.5'), ('5.0', '5.0')], max_length=20)),
                ('spratnost', models.CharField(blank=True, max_length=100, null=True)),
                ('grejanje', models.CharField(choices=[('-', '-'), ('Centralno', 'Centralno'), ('Etažno', 'Etažno'), ('TA', 'TA'), ('Gas', 'Gas'), ('Podno', 'Podno')], max_length=50)),
                ('specijalna_ponuda', models.BooleanField(default=False)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='')),
                ('napomena', models.TextField(blank=True, max_length=1500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostaviPitanje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('pitanje', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SlikaNekretnine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slika', models.ImageField(blank=True, null=True, upload_to='')),
                ('nekretnina', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='App.Nekretnina')),
            ],
        ),
    ]
